"""Storage ports.

Every method takes a tenant_id and every implementation must filter on it.
Tenant scope is enforced at the data boundary, not by the caller remembering.
"""
from __future__ import annotations

from typing import Any, Dict, Optional, Protocol, Sequence, Tuple


class RunRepository(Protocol):
    def create_or_get(self, tenant_id: str, idempotency_key: str,
                      payload: Dict[str, Any]) -> Tuple[Dict[str, Any], bool]: ...
    def get(self, tenant_id: str, run_id: str) -> Optional[Dict[str, Any]]: ...
    def set_state(self, tenant_id: str, run_id: str, state: str,
                  detail: Optional[Dict[str, Any]] = None) -> None: ...
    def record_step(self, tenant_id: str, run_id: str, step_id: str, attempt: int,
                    status: str, detail: Optional[Dict[str, Any]] = None) -> None: ...
    def request_cancel(self, tenant_id: str, run_id: str) -> None: ...
    def is_cancel_requested(self, tenant_id: str, run_id: str) -> bool: ...


class EventStore(Protocol):
    def append(self, tenant_id: str, run_id: str, event: Dict[str, Any]) -> int: ...
    def events(self, tenant_id: str, run_id: str) -> Sequence[Dict[str, Any]]: ...


class ArtifactStore(Protocol):
    def put(self, tenant_id: str, kind: str, payload: Dict[str, Any]) -> str: ...
    def get(self, tenant_id: str, artifact_ref: str) -> Dict[str, Any]: ...


class ReservationStore(Protocol):
    def reserve(self, tenant_id: str, tax_unit_id: str, period: str, amount: str,
                run_id: str, expires_at: str) -> Tuple[bool, str]: ...
    def release(self, tenant_id: str, reservation_id: str) -> None: ...
    def outstanding(self, tenant_id: str, tax_unit_id: str, period: str) -> str: ...
