"""Stable machine-readable codes. Never reword an existing code; add a new one."""

# --- data quality / coverage ---------------------------------------------
MISSING_BASIS = "MISSING_BASIS"
# A review that proposes nothing has nothing for the validator to recompute.
NO_PROPOSAL_TO_VALIDATE = "NO_PROPOSAL_TO_VALIDATE"
MISSING_ACQUISITION_DATE = "MISSING_ACQUISITION_DATE"
BASIS_PROVENANCE_UNVERIFIED = "BASIS_PROVENANCE_UNVERIFIED"
DUPLICATE_LOT = "DUPLICATE_LOT"
INVALID_QUANTITY = "INVALID_QUANTITY"
POSITION_MISMATCH = "POSITION_MISMATCH"
UNRECONCILED_TRANSACTION = "UNRECONCILED_TRANSACTION"
COVERAGE_UNKNOWN = "COVERAGE_UNKNOWN"
COVERAGE_GAP = "COVERAGE_GAP"
UNKNOWN_RELATED_ACCOUNTS = "UNKNOWN_RELATED_ACCOUNTS"
FUTURE_WINDOW_OPEN = "FUTURE_WINDOW_OPEN"
EQUIVALENCE_NOT_ASSESSED = "EQUIVALENCE_NOT_ASSESSED"
CROSS_UNIT_WASH_CONFLICT = "CROSS_UNIT_WASH_CONFLICT"

# --- request / capability ------------------------------------------------
AMBIGUOUS_SUBJECT = "AMBIGUOUS_SUBJECT"
AMBIGUOUS_CONSTRAINT = "AMBIGUOUS_CONSTRAINT"
UNSUPPORTED_SCOPE = "UNSUPPORTED_SCOPE"
UNSUPPORTED_ASSET = "UNSUPPORTED_ASSET"
WRONG_RULE_YEAR = "WRONG_RULE_YEAR"
INFEASIBLE_CONSTRAINTS = "INFEASIBLE_CONSTRAINTS"
CONNECTOR_TEMPORARY_FAILURE = "CONNECTOR_TEMPORARY_FAILURE"
ACCESS_DENIED = "ACCESS_DENIED"
VALIDATION_FAILED = "VALIDATION_FAILED"
BUDGET_RESERVED_ELSEWHERE = "BUDGET_RESERVED_ELSEWHERE"

# --- decisions / restrictions -------------------------------------------
RESTRICTED_SECURITY = "RESTRICTED_SECURITY"
RESTRICTED_ACCOUNT = "RESTRICTED_ACCOUNT"
MIN_HOLDING_PERIOD = "MIN_HOLDING_PERIOD"
WASH_SALE_RISK = "WASH_SALE_RISK"

# --- wash-sale treatment -------------------------------------------------
BASIS_ADJUSTMENT = "BASIS_ADJUSTMENT"
PERMANENT_DISALLOWANCE = "PERMANENT_DISALLOWANCE"

SEVERITY_BLOCKING = "blocking"
SEVERITY_LIMITING = "limiting"
SEVERITY_INFO = "info"
